{% set name = "wtforms-sqlalchemy" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 638f23372e654eded3c19ea605a2d318062e26234772977b9bb1619160eed798

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - wtforms >=3.1
    - sqlalchemy >=1.4

test:
  imports:
    - wtforms_sqlalchemy
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/wtforms/wtforms-sqlalchemy/
  summary: SQLAlchemy tools for WTForms
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
